// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions (customer_id, status)
VALUES ($1, 'WAITING_USER_REPLY')
    RETURNING id, customer_id, status, started_at, last_interaction_at, assigned_agent
`

func (q *Queries) CreateSession(ctx context.Context, customerID uuid.NullUUID) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, customerID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.StartedAt,
		&i.LastInteractionAt,
		&i.AssignedAgent,
	)
	return i, err
}

const getActiveSessionByPhone = `-- name: GetActiveSessionByPhone :one
SELECT cs.id, cs.customer_id, cs.status, cs.started_at, cs.last_interaction_at, cs.assigned_agent
FROM chat_sessions cs
         JOIN customers c ON cs.customer_id = c.id
WHERE c.phone_number = $1 AND cs.status != 'RESOLVED'
LIMIT 1
`

func (q *Queries) GetActiveSessionByPhone(ctx context.Context, phoneNumber string) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByPhone, phoneNumber)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.StartedAt,
		&i.LastInteractionAt,
		&i.AssignedAgent,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, sender_type, content, created_at FROM message_history
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID uuid.NullUUID) ([]MessageHistory, error) {
	rows, err := q.db.QueryContext(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageHistory
	for rows.Next() {
		var i MessageHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message_history (session_id, sender_type, content)
VALUES ($1, $2, $3)
    RETURNING id, session_id, sender_type, content, created_at
`

type InsertMessageParams struct {
	SessionID  uuid.NullUUID  `json:"session_id"`
	SenderType sql.NullString `json:"sender_type"`
	Content    string         `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (MessageHistory, error) {
	row := q.db.QueryRowContext(ctx, insertMessage, arg.SessionID, arg.SenderType, arg.Content)
	var i MessageHistory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE chat_sessions
SET status = $2, last_interaction_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status NullSessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
