// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cleanSessions = `-- name: CleanSessions :exec
UPDATE chat_sessions SET status = 'RESOLVED'
WHERE status IN ('WAITING_USER_REPLY', 'AI_HANDLING')
AND last_interaction_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) CleanSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanSessions)
	return err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (user_id, phone_number, name)
VALUES ($1, $2, $3)
    RETURNING id, phone_number, name, created_at, user_id
`

type CreateCustomerParams struct {
	UserID      uuid.NullUUID `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
	Name        string        `json:"name"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, arg.UserID, arg.PhoneNumber, arg.Name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Name,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions (customer_id, status)
VALUES ($1, 'WAITING_USER_REPLY')
    RETURNING id, customer_id, status, started_at, last_interaction_at, assigned_agent
`

func (q *Queries) CreateSession(ctx context.Context, customerID uuid.NullUUID) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, customerID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.StartedAt,
		&i.LastInteractionAt,
		&i.AssignedAgent,
	)
	return i, err
}

const getActiveSessionByPhone = `-- name: GetActiveSessionByPhone :one
SELECT cs.id, cs.customer_id, cs.status, cs.started_at, cs.last_interaction_at, cs.assigned_agent
FROM chat_sessions cs
         JOIN customers c ON cs.customer_id = c.id
WHERE c.user_id = $1 AND c.phone_number = $2 AND cs.status != 'RESOLVED'
LIMIT 1
`

type GetActiveSessionByPhoneParams struct {
	UserID      uuid.NullUUID `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
}

func (q *Queries) GetActiveSessionByPhone(ctx context.Context, arg GetActiveSessionByPhoneParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByPhone, arg.UserID, arg.PhoneNumber)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.StartedAt,
		&i.LastInteractionAt,
		&i.AssignedAgent,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, phone_number, name, created_at, user_id FROM customers WHERE user_id = $1 AND phone_number = $2 LIMIT 1
`

type GetCustomerByPhoneParams struct {
	UserID      uuid.NullUUID `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByPhone, arg.UserID, arg.PhoneNumber)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Name,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, sender_type, content, created_at FROM message_history
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID uuid.NullUUID) ([]MessageHistory, error) {
	rows, err := q.db.QueryContext(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageHistory
	for rows.Next() {
		var i MessageHistory
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message_history (session_id, sender_type, content)
VALUES ($1, $2, $3)
    RETURNING id, session_id, sender_type, content, created_at
`

type InsertMessageParams struct {
	SessionID  uuid.NullUUID  `json:"session_id"`
	SenderType sql.NullString `json:"sender_type"`
	Content    string         `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (MessageHistory, error) {
	row := q.db.QueryRowContext(ctx, insertMessage, arg.SessionID, arg.SenderType, arg.Content)
	var i MessageHistory
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE chat_sessions
SET status = $2, last_interaction_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status NullSessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
