// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type SessionStatus string

const (
	SessionStatusIDLE             SessionStatus = "IDLE"
	SessionStatusWAITINGUSERREPLY SessionStatus = "WAITING_USER_REPLY"
	SessionStatusAIHANDLING       SessionStatus = "AI_HANDLING"
	SessionStatusHUMANHANDLING    SessionStatus = "HUMAN_HANDLING"
	SessionStatusRESOLVED         SessionStatus = "RESOLVED"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type ChatSession struct {
	ID                uuid.UUID         `json:"id"`
	CustomerID        uuid.NullUUID     `json:"customer_id"`
	Status            NullSessionStatus `json:"status"`
	StartedAt         sql.NullTime      `json:"started_at"`
	LastInteractionAt sql.NullTime      `json:"last_interaction_at"`
	AssignedAgent     sql.NullString    `json:"assigned_agent"`
}

type Customer struct {
	ID          uuid.UUID     `json:"id"`
	PhoneNumber string        `json:"phone_number"`
	Name        string        `json:"name"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UserID      uuid.NullUUID `json:"user_id"`
}

type MessageHistory struct {
	ID         uuid.UUID      `json:"id"`
	SessionID  uuid.NullUUID  `json:"session_id"`
	SenderType sql.NullString `json:"sender_type"`
	Content    string         `json:"content"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	WhatsmeowJid sql.NullString `json:"whatsmeow_jid"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	IsActive     bool           `json:"is_active"`
	IsAdmin      bool           `json:"is_admin"`
}
