// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, is_admin)
VALUES ($1, $2, $3)
    RETURNING id, email, password_hash, whatsmeow_jid, created_at, is_active, is_admin
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WhatsmeowJid,
		&i.CreatedAt,
		&i.IsActive,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, whatsmeow_jid, created_at, is_active, is_admin FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WhatsmeowJid,
		&i.CreatedAt,
		&i.IsActive,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, whatsmeow_jid, created_at, is_active, is_admin FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WhatsmeowJid,
		&i.CreatedAt,
		&i.IsActive,
		&i.IsAdmin,
	)
	return i, err
}

const listPairedUsers = `-- name: ListPairedUsers :many
SELECT id, email, password_hash, whatsmeow_jid, created_at, is_active, is_admin FROM users WHERE whatsmeow_jid IS NOT NULL
`

func (q *Queries) ListPairedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPairedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.WhatsmeowJid,
			&i.CreatedAt,
			&i.IsActive,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2 WHERE id = $1
`

type SetUserAdminParams struct {
	ID      uuid.UUID `json:"id"`
	IsAdmin bool      `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserWhatsmeowJID = `-- name: SetUserWhatsmeowJID :exec
UPDATE users SET whatsmeow_jid = $2 WHERE id = $1
`

type SetUserWhatsmeowJIDParams struct {
	ID           uuid.UUID      `json:"id"`
	WhatsmeowJid sql.NullString `json:"whatsmeow_jid"`
}

func (q *Queries) SetUserWhatsmeowJID(ctx context.Context, arg SetUserWhatsmeowJIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserWhatsmeowJID, arg.ID, arg.WhatsmeowJid)
	return err
}
